/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ejercicio_if_3;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        
        Scanner miScan = new Scanner(System.in);
        
        System.out.println("Introduzca el número de horas trabajadas: ");
        int horas = miScan.nextInt();
        
        int salario;
        
        if(horas <= 40){
            
            salario = horas * 15;
            System.out.println("Su salario es de: " + salario + "€");
        }
        else {
            salario = horas * 15;
            int horasExtra = horas - 40;
            int salarioExtendido = horasExtra * 5;
            salario = salario + salarioExtendido;
            
            System.out.println("Su salario es de: " + salario + "€");
        }
    }
}
